---
include:
  - https://salsa.debian.org/salsa-ci-team/pipeline/raw/master/recipes/debian.yml

variables:
  RELEASE: 'unstable'
  SALSA_CI_DISABLE_APTLY: 0
  SALSA_CI_DISABLE_AUTOPKGTEST: 0
  SALSA_CI_DISABLE_BLHC: 1
  SALSA_CI_DISABLE_LINTIAN: 0
  SALSA_CI_DISABLE_PIUPARTS: 0
  SALSA_CI_DISABLE_DEBREBUILD: 0
  SALSA_CI_DISABLE_BUILD_PACKAGE_ALL: 0
  SALSA_CI_DISABLE_BUILD_PACKAGE_ANY: 0
  SALSA_CI_ENABLE_VALIDATE_PACKAGE_CLEAN_UP: 1
